### ISSUE TITLE
Optimize the repo with folders (For non coders only)

### ISSUE THREAD

**Issue by SubhojeetDas1107** [SubhojeetDas1107/Hacktoberfest2022#8]

**Comment by Rohitsingh385** [comment]
hi can you assign me with this work? you can check my profile ik my stuffs pretty well :D

**Comment by SubhojeetDas1107** [comment]
Well. I want to assign this task to a beginner so that he or she will gain experience... You can contribute your other projects in another open issue :-)

**Comment by Rohitsingh385** [comment]
😅okaye sure do u have any projects?

**Comment by SubhojeetDas1107** [comment]
You can contribute your projects in other PRs/Issue

**Comment by Rohitsingh385** [comment]
Hey can you tell what i have to do like do i have to create separate folders for Cpp and python and add the files into that folder?

**Comment by SubhojeetDas1107** [comment]
Need folders like programs, frontend, ML and other domains with folder program containing sub folders having languages

**Comment by Rohitsingh385** [comment]
Okaye 👍
